server:
  port: 8099

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-mysql-db2.cdmssvujvy8y.ap-northeast-2.rds.amazonaws.com:3306/p21suckjo

    username: jichang23
    password: dlwlckd12

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      location: C:\Users\Public\PoliceOfficeUploadFiles\Files

  profiles:
    include: oauth


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


