version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/p21suckjo/
permissions:
  - object: /home/ec2-user/p21suckjo/
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
